[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=80.0.0", "wheel>=0.45.0"]

[dependency-groups]
algorithm-and-notebooks = [
    "jupyter>=1.1.1",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    "tqdm>=4.68.3",
]
dev = [
    "faker>=37.5.3",
    "pre-commit>=4.2.0",
    "pytest-cov>=6.2.1",
    "pytest-env (>=1.1.5,<2.0.0)",
    "pytest-mock>=3.14.1",
    "pytest>=8.3.4",
    "ruff>=0.12.0",
    "ty>=0.0.69",
]

[project]
authors = [
    {email = "k.hair@ucl.ac.uk", name = "Kaitlyn Hair"},
    {email = "n.loynes@ucl.ac.uk", name = "Nik Loynes"},
]
dependencies = [
    "destiny-sdk>=0.9.0",
    "jellyfish>=1.2.0",
    "loguru>=0.7.3",
    "pydantic-extra-types>=2.10.5",
    "pydantic-settings[yaml]>=2.10.1",
    "pydantic>=2.11.7",
    "python-semantic-release>=10.6.1",
    "rapidfuzz>=3.14.5",
]
description = "A suite of tools for deduplicating DESTINY Works"
name = "destiny-deduper"
readme = "README.md"
requires-python = ">=3.12.11"
version = "0.2.2"

[tool.pytest.ini_options]
addopts = ["--color=yes", "--import-mode=importlib", "--verbose"]
pythonpath = "."
testpaths = ["tests"]

[tool.ruff]
extend-exclude = ["/notebooks", "app/migrations/versions/*.py", "deduplication_workflows.md", "docs/*.py"]
fix = true
force-exclude = true
target-version = "py312"
lint.ignore = [
    "ANN003", # kwargs type annotation required
    "ARG002", # kwargs unused
    "COM812", # trailing commas (ruff-format recommended)
    "CPY001", # copyright notice... bit OTT atm, copyright is in repo
    "D104", # module docstring
    "D203", # no-blank-line-before-class
    "D205", # missing-blank-line-after-summary
    "D212", # multi-line-summary-first-line
    "D403", # forcing upper-case
    "D407", # removed dashes lines under sections
    "D417", # argument description in docstring (unreliable)
    "E501", # let's keep this for now (long lines)
    "FIX002", # implicit trust that TODOs are not trivial, or else they would be fixed
    "ISC001", # simplify implicit str concatenation (ruff-format recommended)
    "TC003", # Runtime imports required by Pydantic model evaluation
    "TD002", # name for TO DO
    "TD003", # pedantic issue number requester in to dos
]
lint.per-file-ignores = {"tests*" = [
    "ANN001", # No return type annotation
    "ANN201", # No return type annotation
    "ANN202", # no return type ann for private funcs
    "ARG001", # Unused function argument
    "ARG005", # kwargs and args unused
    "D100", # Missing docstring in public module
    "D103", # Missing docstring in public function
    "INP001", # File is part of an implicit namespace package.
    "PLR0913", # Too many arguments in function definition
    "PLR2004", # Magic value used in comparison
    "S101", # Use of `assert` detected,
]}
lint.select = ["ALL"]
lint.mccabe.max-complexity = 18
lint.pep8-naming.classmethod-decorators = ["classmethod"]

[tool.semantic_release]
allow_zero_version = true
build_command = """
    uv lock --upgrade-package "$PACKAGE_NAME"
    git add uv.lock
    uv build
"""
tag_format = "{version}"
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.package-data]
destiny_deduper = [".config.yaml"]

[tool.setuptools.packages.find]
exclude = ["misc*", "notebooks*", "tests*"]
include = ["destiny_deduper*"]
where = ["."]

[tool.tomlsort]
all = true
spaces_indent_inline_array = 4
trailing_comma_inline_array = true
overrides."project.classifiers".inline_arrays = false
overrides."tool.coverage.paths.source".inline_arrays = false

[tool.ty.src]
exclude = [
    "destiny_deduper/algorithm",
    "notebooks",
    "notebooks/**",
    "tests",
    "tests/**",
]

[[tool.uv.index]]
explicit = true
name = "testpypi"
publish-url = "https://test.pypi.org/legacy/"
url = "https://test.pypi.org/simple/"
